# Generated by Django 5.0.2 on 2024-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_book_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='items.genre'),
        ),
    ]
