# Generated by Django 5.0.2 on 2024-03-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_book_genre'),
        ('items', '0003_alter_book_genre_savebook_delete_userbook'),
    ]

    operations = [
    ]
